### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#12]
http://i.imgur.com/uzU1e71.png

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 318, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 209, in parse_comments
    give_more_info(comment)
  File "info_bot_nsfw.py", line 134, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 74, in get_nonspam_links
    domain =  get_domain(link)
  File "info_bot_nsfw.py", line 60, in get_domain
    group = result.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 318, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 209, in parse_comments
    give_more_info(comment)
  File "info_bot_nsfw.py", line 134, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 74, in get_nonspam_links
    domain =  get_domain(link)
  File "info_bot_nsfw.py", line 60, in get_domain
    group = result.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tek0011** [comment]
Link it fails on - `IC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" `

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 318, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 209, in parse_comments
    give_more_info(comment)
  File "info_bot_nsfw.py", line 134, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 74, in get_nonspam_links
    domain =  get_domain(link)
  File "info_bot_nsfw.py", line 60, in get_domain
    group = result.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 320, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 209, in parse_comments
    give_more_info(comment)
  File "info_bot_nsfw.py", line 127, in give_more_info
    google_formatted = format_results(get_google_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 75, in get_nonspam_links
    if ((domain not in [get_domain(k) for k in blacklist]) and (domain not in hard_blacklist) and (not any(i in domain for i in blacklist))) or (domain in whitelist):
  File "info_bot_nsfw.py", line 60, in get_domain
    group = result.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by jacobstein123** [comment]
This seems to be pointing to code from two commits ago
