### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#15]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 299, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 188, in parse_comments
    comment = r.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments[0]
IndexError: list index out of range

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 311, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 196, in parse_comments
    comment = r.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments[0]
IndexError: list index out of range

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 311, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 196, in parse_comments
    comment = r.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments[0]
IndexError: list index out of range

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 318, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 209, in parse_comments
    give_more_info(comment)
  File "info_bot_nsfw.py", line 134, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 74, in get_nonspam_links
    domain =  get_domain(link)
  File "info_bot_nsfw.py", line 60, in get_domain
    group = result.group()
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tek0011** [comment]
`Traceback (most recent call last):
  File "info_bot_nsfw.py", line 318, in <module>
    parse_comments(all_comments)
  File "info_bot_nsfw.py", line 201, in parse_comments
    comment = r.get_submission(url="http://www.reddit.com/r/{0}/comments/{1}/aaaa/{2}".format(comment['subreddit'],comment['link_id'][3:],comment['id'])).comments[0]
IndexError: list index out of range`

**Comment by jacobstein123** [comment]
It now checks if get_submission creates a valid (nonempty) comment object before continuing which should correct this error.
