### ISSUE TITLE
praw.errors.APIException: (NO_TEXT) `we need something here` on field `text`

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#22]
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '', 'thing_id': u't3_334fmf'}
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 363, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 221, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 140, in give_more_info
    karmadecay_formatted = format_results(get_karmadecay_results(comment.submission))
  File "info_bot_nsfw.py", line 113, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 77, in get_nonspam_links
    submission.add_comment(link)
  File "C:\Python27\lib\site-packages\praw\objects.py", line 1019, in add_comment
    response = self.reddit_session._add_comment(self.fullname, text)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "C:\Python27\lib\site-packages\praw\__init__.py", line 2173, in _add_comment
    retry_on_error=False)
  File "C:\Python27\lib\site-packages\praw\decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.APIException: (NO_TEXT) `we need something here` on field `text`

**Comment by tek0011** [comment]
http://www.reddit.com/r/redditdev/comments/2immwi/praw_apiexception_no_text/

**Comment by jacobstein123** [comment]
Now checks if the link is empty before posting it.
