### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#23]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 363, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 221, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 137, in give_more_info
    bing_formatted = format_results(get_bing_results(comment.submission))
  File "info_bot_nsfw.py", line 37, in get_bing_results
    response_text = opener.open("https://www.bing.com/images/searchbyimage?FORM=IRSBIQ&cbir=sbi&imgurl="+image).read()
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by tek0011** [comment]
retrieving: http://www.reddit.com/user/nsfmostplaces/about/.json
params: None
data: None
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 363, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 221, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 137, in give_more_info
    bing_formatted = format_results(get_bing_results(comment.submission))
  File "info_bot_nsfw.py", line 37, in get_bing_results
    response_text = opener.open("https://www.bing.com/images/searchbyimage?FORM=IRSBIQ&cbir=sbi&imgurl="+image).read()
  File "C:\Python27\lib\urllib2.py", line 437, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by jacobstein123** [comment]
Is this still an issue?

**Comment by tek0011** [comment]
Likely not. I think that was bing. Close it.
