### ISSUE TITLE
UnboundLocalError: local variable 'yandex_formatted' referenced before assignment

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#25]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 396, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 254, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 174, in give_more_info
    if not yandex_formatted: yandex_available = False
UnboundLocalError: local variable 'yandex_formatted' referenced before assignment

**Comment by tek0011** [comment]
Im pretty sure the formatting was just off.  I moved line 175 - yandex_available = False down a line to be in the loop

**Comment by tek0011** [comment]
Nope, that was not the issue, still same error:

Traceback (most recent call last):
  File "info_bot_nsfw.py", line 397, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 255, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 174, in give_more_info
    if not yandex_formatted:
UnboundLocalError: local variable 'yandex_formatted' referenced before assignment

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 414, in <module>
    find_username_mentions()
  File "info_bot_nsfw.py", line 271, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 191, in give_more_info
    if not yandex_formatted: yandex_available = False
UnboundLocalError: local variable 'yandex_formatted' referenced before assignment

**Comment by jacobstein123** [comment]
should be fixed with the addition of initiating empty lists
