### ISSUE TITLE
urllib2.HTTPError: HTTP Error 503: Service Unavailable

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#31]
http:**38.media.tumblr.com*369fad6b18c7e3b5ac5b38c3913c44d0*tumblr_naphhzL6TM1rh0602o1_r1_500.gif
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 466, in <module>
    main()
  File "info_bot_nsfw.py", line 450, in main
    find_username_mentions()
  File "info_bot_nsfw.py", line 301, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 190, in give_more_info
    results = eval(urllib2.urlopen("https://sleepy-tundra-5659.herokuapp.com/search/"+link).read())
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 466, in <module>
    main()
  File "info_bot_nsfw.py", line 450, in main
    find_username_mentions()
  File "info_bot_nsfw.py", line 301, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 190, in give_more_info
    results = eval(urllib2.urlopen("https://sleepy-tundra-5659.herokuapp.com/search/"+link).read())
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by jacobstein123** [comment]
This should be fixed from the last commit, so I'll close it for now. If it recurs, let's reopen it.
