### ISSUE TITLE
socket.error: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by tek0011** [tek0011/RedditInfoBot#33]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 466, in <module>
    main()
  File "info_bot_nsfw.py", line 444, in main
    all_comments = get_all_comments(stream)
  File "info_bot_nsfw.py", line 372, in get_all_comments
    a = session_client.get(stream, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 605, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/local/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer
[root@redditbots redditbot]#

**Comment by tek0011** [comment]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 473, in <module>
    main()
  File "info_bot_nsfw.py", line 451, in main
    all_comments = get_all_comments(stream)
  File "info_bot_nsfw.py", line 379, in get_all_comments
    a = session_client.get(stream, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 605, in send
    r.content
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 750, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/local/lib/python2.7/site-packages/requests/models.py", line 673, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 307, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 243, in read
    data = self._fp.read(amt)
  File "/usr/local/lib/python2.7/httplib.py", line 612, in read
    s = self.fp.read(amt)
  File "/usr/local/lib/python2.7/socket.py", line 384, in read
    data = self._sock.recv(left)
socket.error: [Errno 104] Connection reset by peer

**Comment by jacobstein123** [comment]
The bot will try again if it gets a socket error. Should fix this issue.
